### ISSUE TITLE
Visual composer header is not working with theme customizer option

### ISSUE THREAD

**Issue by kaleshwaryadav** [VisualComposer/visual-composer-starter#204]
Hi,
I have created header in visual composer  but its not working  with the theme customize option as default theme header is working so kindly suggest me please. how can i resolve it.

**Comment by veidenbaums** [comment]
Hi!

Could you please be more detailed about the issue? At the momen't I'm not quite sure that I got your ide right, maybe you can attach some screenshots of the issue?
