### ISSUE TITLE
Is this theme actually for WPBakery, or Visual Composer?

### ISSUE THREAD

**Issue by martonlente** [VisualComposer/visual-composer-starter#241]
Hello,

I'm new to both WPBakery, and Visual Composer. I've discovered this starter theme, however I'm not sure if it's actually for WPBakery, or Visual Composer?

The reason why I'm uncertain, is that this repository dates back to 2016, however Visual Composer (the new product) – as far as I know – was only released later, in 2017.

Sorry for my dummy question, and thanks for the explanation in advance! If this theme is truly for Visual Composer (the new product), then do you have a starter theme also for WPBakery?

Kind regards,
Márton Lente

**Comment by AngeIII** [comment]
The Visual Composer Website Builder development time started before the 2016, so yes, this theme relates only to Visual Composer Website Builder.

**Comment by martonlente** [comment]
Thanks @AngeIII for the explanation! :)
