### ISSUE TITLE
Problem with magnifying Product image in woocommerce

### ISSUE THREAD

**Issue by joelalexandersson** [VisualComposer/visual-composer-starter#253]
There is a problem with the single product image in woocommerce when you are trying to magnify the image on a mobile device. The image opens up magnified but is then stuck. Also no button to close the image.

**Comment by nikitahl** [comment]
Could not replicate.
Checked on iPhone 6s, iOS 13.3, Safari 13

Requires more detail:

- steps to replicate
- mobile device model
- mobile device software version
- mobile device browser
