### ISSUE TITLE
Weird fixed header issue while loading DOM

### ISSUE THREAD

**Issue by loremipsum31** [VisualComposer/visual-composer-starter#256]
There is a small bad effect on the fixed header in case you have a big landing page with lot of other stuff in JS, combined with cache, cdn...
The header nav look wierd while we are loading the DOM. In our case the header is on the left and become fixed.
The problem is related to the usage of $navBar.addClass( 'fixed' ); in functions.js

To skip the problem here, we removed it from the functions.js and we had a conditionnal test on header.php
<nav class="navbar <?php echo(in_array('fixed-header', get_body_class()))?'fixed':'';?>">

Maybe a better solution ?

**Comment by loremipsum31** [comment]
Here this is what we do : https://github.com/VisualComposer/visual-composer-starter/pull/257

**Comment by nikitahl** [comment]
Closing, the issue has been solved in #257
