### ISSUE TITLE
render-blocking occurring on fonts

### ISSUE THREAD

**Issue by RMAgency100** [VisualComposer/visual-composer-starter#272]
**Describe the bug**

I'm seeing some render-blocking occurring on the fonts since they're loaded after some javascript (all javascript should be loaded last on the page but before ads), and currently it looks like the second item loaded to the page is jquery.js which should be your fonts instead. Due to this, there's about 0.3-second delay in "render-blocking" due to the fonts being loaded afterwards.

Can this be fixed in the next update for the theme?

**To Reproduce**

I'm also seeing a repeat call to one of the fonts at "https://fonts.gstatic.com/s/poiretone/v8/UqyVK80NJXN4zfRgbdfbo55cVw.woff2" which GTMetrix scores the site poorly for. 

Can the repeat call be removed to shave off about 1.5 seconds on the test as seen here: http://cl.ly/656d1fe8c476 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nikitahl** [comment]
Thank you for reporting, we will investigate this issue.

**Comment by RMAgency100** [comment]
You're welcome.


[image: photo]
*Christian McGinty*
Director, Restaurant Marketing Agency
p:+44 (0) 20 3475 5182 | e:christian@restaurantmarketingagency.co.uk | w:
https://restaurantmarketingagency.co.uk/
<http://www.facebook.com/RestaurantMarketingAgency/>
<http://twitter.com/@Rest_MktgAgency>
<http://www.pinterest.co.uk/Rest_MktgAgency/>
<http://www.linkedin.com/company/restaurant-marketing-agency>
<http://plus.google.com/+RestaurantMarketingAgency>
Restaurant Marketing Blog Instagram Strategy For Restaurant: Growth Hack
With Photos
<https://restaurantmarketingagency.co.uk/blog/instagram-strategy-for-restaurant/>

IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.
<https://uk.linkedin.com/in/christianmcginty>
<https://www.facebook.com/RecipeSocialUK>   <http://Rest_MktgAgency>
Get your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own&srcid=4637740537741312>

**Comment by veidenbaums** [comment]
Hi!

Could you please check if the problem is solved now?
