### ISSUE TITLE
Error in Parent Theme on Wordpress 5.5 Update

### ISSUE THREAD

**Issue by gianlucaNIU** [VisualComposer/visual-composer-starter#281]
**Describe the bug**
I just wanted to let you know that there is an error when updating to Wordpress 5.5. Basically vcThemeVars is not being localized to visualcomposer object in visual-composer-starter/js/functions.js line 11 (var vcThemeVars = window.visualcomposerstarter;). This then was causing a problem and this error below in the same file line 194 ($( document.body ).on( 'added_to_cart', function() ......). We had to revert back to Wordpress 5.4.3 for this to work again.

Please let us know when this error is solved and available to update the parent theme and Wordpress 5.5. 

**To Reproduce**
1. Add a product to cart with ajax with Woocommerce
2. Check Console

**Expected behavior**
Add to cart keeps loading

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/52165769/90620533-dfc8f800-e212-11ea-9340-fe16743c3881.png)

**Comment by shaolinshaosson** [comment]
Same for me, not sure Why it happened, some changes to localize script in wordpress?
In functions.php the only localization is on jquery, so I added this to fix it:
`wp_localize_script( 'visualcomposerstarter-script', 'visualcomposerstarter', array(
		'ajax_url' => admin_url( 'admin-ajax.php' )
	) );`
