### ISSUE TITLE
Theme update to accomodate WooCommerce

### ISSUE THREAD

**Issue by GMDOnline** [VisualComposer/visual-composer-starter#285]
**Describe the bug**

I have received the following message from Woocommerce

> Your theme (Visual Composer Starter) contains outdated copies of some WooCommerce template files. These files may need updating to ensure they are compatible with the current version of WooCommerce. Suggestions to fix this:
> 
> Update your theme to the latest version. If no update is available contact your theme author asking about compatibility with the current WooCommerce version.
> If you copied over a template file to change something, then you will need to copy the new version of the template and apply your changes again.
> 

I have been advised to post this on Github

**Comment by nikitahl** [comment]
Hello!
Could you provide more details about your issue, like what version of WooCommerce, Visual Composer Starter and WordPress are you using?

**Comment by GMDOnline** [comment]
Hi there,

~I am using the following Versions:

WooCommerce – Version 4.6.1
Visual Composer Starter - 30.1

Sent from Mail for Windows 10

**Comment by nikitahl** [comment]
Thanks for reporting. We confirm this issue.
We've created a bug in our Backlog and will release a fix in the near future.
This issue will be closed once we merge PR with a fix.
