### ISSUE TITLE
Latest version has created tons of issues on the site

### ISSUE THREAD

**Issue by rtpHarry** [VisualComposer/visual-composer-starter#303]
I don't know what you have done to change the code as the commits are pretty messy and you aren't using the releases/tags feature any more.

When the site updated the theme to the latest version it has caused a ton of issues.

First the nav disappeared, I've managed to get that to come back but now there are lots of display issues. The dropdown icon isn't working, the text is huge, the google fonts are not loading the same:

![image](https://user-images.githubusercontent.com/1038062/126631239-822db4c1-1dbf-4779-8916-7a7fbefc91e2.png)

It's a right mess. I've never had a theme update destroy the site this badly.

**Comment by veidenbaums** [comment]
Hi! Do you use a child theme? Or only the parent theme? 

Additionally, you could try to enable the bootstrap option under theme settings in the customizer. But this should affect something only if you have some modifications.
