### ISSUE TITLE
Font & Style not Working on version 3.2 and newer (works fine with 3.1)

### ISSUE THREAD

**Issue by rizaardiyanto** [VisualComposer/visual-composer-starter#304]
**Describe the bug**
Set the heading via Customizer => Font & Styles did not works fine

**To Reproduce**
1. Create a page
2. Add text block
3. Add some words. 
4. Set it to H2 or any other Heading
5. Go to appearance => Customize => Font style
6. Set the H2 into Oswald, sans serif.
7. The font does not change

**Expected behavior**
https://i.imgur.com/dTWKrgS.png

**Current behaviour**
https://i.imgur.com/AGw6DHL.png

**Comment by dmytro-kovalov** [comment]
Could not replicate this. Version 3.2.2 works fine.
