### ISSUE TITLE
Incorrect button style on products page with WooCommerce Product 3.2 element

### ISSUE THREAD

**Issue by seahunter** [VisualComposer/visual-composer-starter#306]
When I use a default theme with enabled WooCommerce Product 3.2 element, my button styles are breaking.
How to reproduce:
1) Create an archive page via VC
2) Add a WooCommerce 3.2 element
3) Check the styles of the buttons

**Comment by nikitahl** [comment]
Issue fixed https://github.com/VisualComposer/visual-composer-starter/pull/307
