### ISSUE TITLE
Bullet points displayed while using WooCommerce Products 3.2+ element

### ISSUE THREAD

**Issue by iamrohan** [VisualComposer/visual-composer-starter#308]
When using WooCommerce Products 3.2+ element with starter theme, it displays bullet points in top left corner: https://prnt.sc/1uu3ru1

1. Add WooCommerce Products 3.2+ element
2. Check the page output

Expected behavior: Products being displayed without any bullets.

**Comment by nikitahl** [comment]
In this case, need to fix the WooCommerce Products 3.2+ element itself to override the theme styles. 
As well as consider refactoring these bullets as they're made using pseudo-elements that can be displayed anywhere where the lists are used.
