### ISSUE TITLE
style.min.css has .content-wrapper margin: 0 -15px; that adds a scroll bar at the bottom of the screen with an empty gap on the right side of 15px.

### ISSUE THREAD

**Issue by raykai** [VisualComposer/visual-composer-starter#322]
**Describe the bug**
Having the theme settings set to Content Area Size Customization: Full width = Seems to have a bug as it adds a scroll bar at the bottom of the screen with an empty gap on the right side of 15px.

The file style.min.css?ver=3.2.2 at  .content-wrapper has a margin: 0 -15px; removing the -15px fixes the layout.

![Snipaste_2022-05-07_13-14-34](https://user-images.githubusercontent.com/8138894/167265054-a4ecdae2-c1a6-4371-9e0d-18dc323d1731.png)

![Snipaste_2022-05-07_13-15-02](https://user-images.githubusercontent.com/8138894/167265057-53d8856f-5105-4b73-8256-6838bf441cad.png)

![Snipaste_2022-05-07_13-16-22](https://user-images.githubusercontent.com/8138894/167265061-90389b31-2384-446a-8fad-75a87f0cff12.png)

![Snipaste_2022-05-07_13-17-14](https://user-images.githubusercontent.com/8138894/167265071-1a5a23fd-87f1-487f-8b64-2a1a294d84a3.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Set the theme Content Area Size Customization to full width.
2. Add some content for the page.
3. See the scrollbar shown at the bottom of the page.

**Expected behaviour**
The page should not have a gap on the right side that adds a scroll bar at the bottom of the page as the page is bigger than the desktop screen.

**Desktop (please complete the following information):**
 - OS: PC Windows 11
 - Browser chrome, Edge
 - Version latest

**Comment by nikitahl** [comment]
Thank you for reporting. We're able to replicate it. The issue will be closed when the PR with the fix is merged.

**Comment by raykai** [comment]
Any ETA for a Releases update?

**Comment by veidenbaums** [comment]
@raykai we're working on it now :)
