### ISSUE TITLE
Unintended hover underline on images and many other elements, probably in connection with FontManager

### ISSUE THREAD

**Issue by anomalie-paradox** [VisualComposer/visual-composer-starter#335]
Hello,

I reported a bug in combination with the Visual Composer Starter theme via Visual Composer a while ago. I was told that I couldn't report bugs with the theme, only with the plugin. So I'm just posting the history here. Isn't the Visual Composer Starter Theme designed to have maximum compatibility with the plugin? Or is it developed by a different company and just happens to have the same name? The main problem is that when using the font manager, a number of elements such as images, buttons, icons, etc. suddenly get a hover underline that I have to remove every time using CSS. But I don't think they should have that. So maybe you can check that. Thanks.
- - - -
My Text 
For example, images are underlined, which was a bug I had before elsewhere. Could you check right away to see whether these are bugs that can be fixed? Then I wouldn't have to create a new ticket for every error.

Response from Visual Composer

The issue such as the one where an underline is added for post images, seems to be specific to the theme (Visual Composer Starter). When a default such as twenty twenty four is used, there seems to be no underline added to it.

You can comment your CSS that is used and then check if the same issue persists with the default twenty twenty four theme. If it does not, then it confirms that the issue is specific to the starter theme that is being used.

If you find any issues related to Visual Composer starter theme, then you can report it here: https://github.com/VisualComposer/visual-composer-starter/issues so that their bug-fixes can be included in the next theme update.

While our starter theme is specifically optimized for use with Visual Composer and we highly recommend it for optimal performance, it's important to note that themes may introduce their own styles to the content they render. 
For example, you've mentioned the issue with post images having underlines, which may not align with your preferences.

To address this, there are a couple of options available. One approach is to create a child theme and customize the styles within the child theme's style.css file to remove any unwanted styling. Alternatively, you can also raise this issue with the GitHub repository of the starter theme, allowing our development team to address it in future updates of the theme.

Your ticket #52121 has been updated. To add additional comments, reply to this email.

**Comment by nikitahl** [comment]
Hello!
Which elements do you have in mind when you're saying:
> elements such as images, buttons, icons, etc. suddenly get a hover underline
Are you referring to theme elements (added via Gutenberg) or do you have issues with Visual Composer elements?

**Comment by anomalie-paradox** [comment]
Hello,

I mean the VC elements of course, which is why I actually reported a bug. But Rohan from VC support-team said that I can't report any problems with the theme to him, but for whatever reason I have to do it on GitHub.

I assumed that the VC Starter Theme was developed by VC to ensure maximum compatibility with the VC plugin.

Rohan now tells me that the problem does not occur with the twenty twenty four theme. So I ask myself what the starter theme is good for if it works worse than the standard WordPress themes.

The problem is this: As soon as the VC font manager is activated, a number of elements suddenly have an underline and a hover behavior. Such as simple galleries or images, icon-buttons, etc. Both in the normal and hover state. Also the various controls such as the close button on the lightboxes, etc. I think I also had the problem with the close button on the burger menu. I'm attaching a few screenshots.

I've had this problem with ALL websites I've built with VC. No extra plugins or anything else, just the VC plugin and starter theme.

But even with the best will in the world, I don't have the time to test every single element. Don't you have some kind of standard installation with a page where all the elements are placed? You can definitely test it there. That's actually the developer's job and not mine as a paying customer. 

So far, I've just written myself some CSS hacks to solve the problem with individual elements that I need for the current customer project. Because I don't have the time to write a detailed report with screenshots etc. every time and, above all, to report problems in two different ways.

![Bildschirmfoto 2024-07-10 um 10 00 32](https://github.com/VisualComposer/visual-composer-starter/assets/137199341/11d1ed78-8ce7-49b0-97e6-9a4c59f41739)
![Bildschirmfoto 2024-07-10 um 10 02 42](https://github.com/VisualComposer/visual-composer-starter/assets/137199341/026b217a-6927-4300-8afd-47a356c3c58b)
![Bildschirmfoto 2024-07-10 um 10 03 29](https://github.com/VisualComposer/visual-composer-starter/assets/137199341/ec69402c-97d7-4738-949f-80b57a3505f1)
![Bildschirmfoto 2024-07-10 um 10 04 13](https://github.com/VisualComposer/visual-composer-starter/assets/137199341/1642f474-3528-4cd1-8e45-8bfd0e63ffb0)
![Bildschirmfoto 2024-07-10 um 10 04 16](https://github.com/VisualComposer/visual-composer-starter/assets/137199341/69946451-2c97-47c0-9448-636515725c6c)

**Comment by anomalie-paradox** [comment]
I've tried to find out where the underlines come from. I don't know if the CSS instruction comes from VC or the theme, but if I throw it into a CSS validator, a number of errors are output. Try it yourself here: https://codebeautify.org/cssvalidate

.vcwb-font-manager :not(li[class*="menu"], div[class*="brand"]) > a:not(.vce-single-image-inner, [class*="vce-post-grid"], [class*="button"], [class*="logo"], [class*="icon"]) {

border-bottom-width: 0;

border-bottom-style: none;

border-bottom-color: transparent;
}

.vcwb-font-manager :not(li[class*="menu"], div[class*="brand"]) > a:not(.vce-single-image-inner, [class*="vce-post-grid"], [class*="button"], [class*="logo"], [class*="icon"]):hover, .vcwb-font-manager :not(li[class*="menu"], div[class*="brand"]) > a:not(.vce-single-image-inner, [class*="vce-post-grid"], [class*="button"], [class*="logo"], [class*="icon"]):focus {

border-bottom: none;
}

**Comment by nikitahl** [comment]
Hello!

Upon checking we've found a bug, that affects elements such as Image Gallery and Mono Social Icons by adding an underline for link elements.

We've added this bug to our Backlog and will fix it for the upcoming release.

As this case is related to the Font Manager feature of the Visual Composer plugin, I'm closing this issue.
